### ISSUE TITLE
Unable to create a spark job

### ISSUE THREAD

**Issue by Andromelus** [saagie/api-saagie#123]
**Describe the bug**

With saagieapi 1.1.0, trying to create a job with pyspark 2.4 and python 3.7 fails.

Here is the script used:

```
from saagieapi import SaagieApi
import os


saagie = SaagieApi(url_saagie="ULR",
                   id_platform=2,
                   user=os.environ["MATMUT_SAAGIE_LOGIN"],
                   password=os.environ["MATMUT_SAAGIE_PWd"],
                   realm="REALM"
                   )

catalog = "Saagie"
techno = "spark"
runtime = "2.4"
project_id = "PROJECT ID"
extra_tech = "Python"
extra_runtime = "3.7"

saagie.jobs.create(
    job_name="job_name",
    project_id=project_id,
    file="./version",
    description="",
    category="Extraction",
    technology_catalog=catalog,
    technology=techno,
    runtime_version=runtime,
    command_line="echo toto",
    release_note="release_note",
    extra_technology=extra_tech,
    extra_technology_version=extra_runtime
)

```

The current output is:

```
$ python test.py
30/06/2022 15:16:52 [INFO] ✅ Successfully connected to your platform URL
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    saagie.jobs.create(
  File "C:\Users\castelain.florianext\Documents\anaconda\lib\site-packages\saagieapi\jobs\jobs.py", line 283, in create
    available_runtimes = [
  File "C:\Users\castelain.florianext\Documents\anaconda\lib\site-packages\saagieapi\jobs\jobs.py", line 286, in <listcomp>
    if tech["available"] is True
KeyError: 'available'
```

printing `self.saagie_api.get_runtimes(params["technologyId"])` gives:

`{'technology': {'__typename': 'SparkTechnology', 'contexts': [{'label': '2.4'}, {'label': '3.0'}, {'label': '3.1'}]}}`

Where there is obviously no "available" key.

**Expected behavior**

The job creation should work as expected.

**Comment by saagie-service** [comment]
Trello card: [[#123] Unable to create a spark job](https://trello.com/c/iwrUQcE5)

**Comment by tquiviger** [comment]
Issue has been fixed with release 1.1.2
